---
- name: Handle installation for Debian
  ansible.builtin.import_tasks: install-debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - act_runner

- name: Handle installation for Windows
  ansible.builtin.import_tasks: install-windows.yml
  when: ansible_facts['os_family']|lower == 'windows'
  tags:
    - act_runner

- name: Handle service for Debian
  ansible.builtin.import_tasks: service-debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - act_runner

- name: Handle service for Windows
  ansible.builtin.import_tasks: service-windows.yml
  when: ansible_facts['os_family']|lower == 'windows'
  tags:
    - act_runner